# Generated by Django 5.0.6 on 2024-07-26 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_is_email_verified'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('set_active', 'Может блокировать пользователей сервиса.')]},
        ),
    ]
