# Generated by Django 5.0.6 on 2024-07-24 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('second_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Отчество')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок рассылки')),
                ('message', models.TextField(verbose_name='Содержание рассылки')),
                ('status', models.CharField(choices=[('Новый', 'Новый'), ('Отправлен', 'Отправлен'), ('Отклонен', 'Отклонен')], default='Новый', max_length=10, verbose_name='Статус рассылки')),
                ('scheduled_time', models.DateTimeField(verbose_name='Дата и время отправки')),
                ('periodicity', models.CharField(choices=[('Ежедневно', 'Ежедневно'), ('Еженедельно', 'Еженедельно'), ('Ежемесячно', 'Ежемесячно')], default='Ежедневно', max_length=15, verbose_name='Периодичность расылки')),
                ('clients', models.ManyToManyField(to='main.client', verbose_name='Клиенты')),
            ],
            options={
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылки',
            },
        ),
        migrations.CreateModel(
            name='MailingAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время попытки отправки')),
                ('status', models.CharField(choices=[('Новый', 'Новый'), ('Отправлен', 'Отправлен'), ('Отклонен', 'Отклонен')], max_length=10, verbose_name='Статус попытки отправки')),
                ('log_message', models.TextField(blank=True, null=True, verbose_name='Лог сообщения')),
                ('mailing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.mailing', verbose_name='Рассылка')),
            ],
            options={
                'verbose_name': 'Попытка отправки рассылки',
                'verbose_name_plural': 'Попытки отправки рассылок',
            },
        ),
    ]
