# Generated by Django 5.0.6 on 2024-06-25 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_mailingattempt_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailing',
            name='periodicity',
            field=models.CharField(choices=[('Ежедневно', 'Ежедневно'), ('Еженедельно', 'Еженедельно'), ('Ежемесячно', 'Ежемесячно')], default='Ежедневно', max_length=15, verbose_name='Периодичность расылки'),
        ),
    ]
