# Generated by Django 5.0.6 on 2024-06-25 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_mailing_periodicity'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailingattempt',
            name='next_attempt',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата и время следующей попытки'),
        ),
    ]
