# Generated by Django 5.0.6 on 2024-06-25 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_mailingattempt_next_attempt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailingattempt',
            name='next_attempt',
        ),
        migrations.AddField(
            model_name='mailingattempt',
            name='log_message',
            field=models.TextField(blank=True, null=True, verbose_name='Лог сообщения'),
        ),
    ]
